# Parameter names
param_names = [
    "awCap_scalar",
    "wiltingp_scalar",
    "alpha_claycoef",
    "alpha_sandcoef",
    "alpha_siltcoef",
    "betaHBV_claycoef",
    "betaHBV_sandcoef",
    "betaHBV_siltcoef",
    "betaHBV_elevcoef",
    "GS_start_corn",
    "GS_end_corn",
    "L_ini_corn",
    "L_dev_corn",
    "L_mid_corn",
    "Kc_ini_corn",
    "Kc_mid_corn",
    "Kc_end_corn",
    "Kmin_corn",
    "Kmax_corn",
    "GS_start_cotton",
    "GS_end_cotton",
    "L_ini_cotton",
    "L_dev_cotton",
    "L_mid_cotton",
    "Kc_ini_cotton",
    "Kc_mid_cotton",
    "Kc_end_cotton",
    "Kmin_cotton",
    "Kmax_cotton",
    "GS_start_rice",
    "GS_end_rice",
    "L_ini_rice",
    "L_dev_rice",
    "L_mid_rice",
    "Kc_ini_rice",
    "Kc_mid_rice",
    "Kc_end_rice",
    "Kmin_rice",
    "Kmax_rice",
    "GS_start_sorghum",
    "GS_end_sorghum",
    "L_ini_sorghum",
    "L_dev_sorghum",
    "L_mid_sorghum",
    "Kc_ini_sorghum",
    "Kc_mid_sorghum",
    "Kc_end_sorghum",
    "Kmin_sorghum",
    "Kmax_sorghum",
    "GS_start_soybeans",
    "GS_end_soybeans",
    "L_ini_soybeans",
    "L_dev_soybeans",
    "L_mid_soybeans",
    "Kc_ini_soybeans",
    "Kc_mid_soybeans",
    "Kc_end_soybeans",
    "Kmin_soybeans",
    "Kmax_soybeans",
    "GS_start_wheat",
    "GS_end_wheat",
    "L_ini_wheat",
    "L_dev_wheat",
    "L_mid_wheat",
    "Kc_ini_wheat",
    "Kc_mid_wheat",
    "Kc_end_wheat",
    "Kmin_wheat",
    "Kmax_wheat",
    "Kmin_cropland_other",
    "Kmax_cropland_other",
    "Kmin_evergreen_needleleaf",
    "Kmax_evergreen_needleleaf",
    "Kmin_evergreen_broadleaf",
    "Kmax_evergreen_broadleaf",
    "Kmin_deciduous_needleleaf",
    "Kmax_deciduous_needleleaf",
    "Kmin_deciduous_broadleaf",
    "Kmax_deciduous_broadleaf",
    "Kmin_mixed_forest",
    "Kmax_mixed_forest",
    "Kmin_woodland",
    "Kmax_woodland",
    "Kmin_wooded_grassland",
    "Kmax_wooded_grassland",
    "Kmin_closed_shurbland",
    "Kmax_closed_shurbland",
    "Kmin_open_shrubland",
    "Kmax_open_shrubland",
    "Kmin_grassland",
    "Kmax_grassland",
    "Kmin_barren",
    "Kmax_barren",
    "Kmin_urban",
    "Kmax_urban",
]

# param_names_vic = [
#     "awCap_sand",
#     "awCap_loamy_sand",
#     "awCap_sandy_loam",
#     "awCap_silt_loam",
#     "awCap_silt",
#     "awCap_loam",
#     "awCap_sandy_clay_loam",
#     "awCap_silty_clay_loam",
#     "awCap_clay_loam",
#     "awCap_sandy_clay",
#     "awCap_silty_clay",
#     "awCap_clay",
#     "wiltingp_sand",
#     "wiltingp_loamy_sand",
#     "wiltingp_sandy_loam",
#     "wiltingp_silt_loam",
#     "wiltingp_silt",
#     "wiltingp_loam",
#     "wiltingp_sandy_clay_loam",
#     "wiltingp_silty_clay_loam",
#     "wiltingp_clay_loam",
#     "wiltingp_sandy_clay",
#     "wiltingp_silty_clay",
#     "wiltingp_clay",
#     # "awCap_claycoef",
#     # "awCap_sandcoef",
#     # "awCap_siltcoef",
#     # "wiltingp_claycoef",
#     # "wiltingp_sandcoef",
#     # "wiltingp_siltcoef",
#     "alpha_claycoef",
#     "alpha_sandcoef",
#     "alpha_siltcoef",
#     "betaHBV_claycoef",
#     "betaHBV_sandcoef",
#     "betaHBV_siltcoef",
#     "betaHBV_elevcoef",
#     "GS_start_corn",
#     "GS_end_corn",
#     "L_ini_corn",
#     "L_dev_corn",
#     "L_mid_corn",
#     "Kc_ini_corn",
#     "Kc_mid_corn",
#     "Kc_end_corn",
#     "Kmin_corn",
#     "Kmax_corn",
#     "GS_start_cotton",
#     "GS_end_cotton",
#     "L_ini_cotton",
#     "L_dev_cotton",
#     "L_mid_cotton",
#     "Kc_ini_cotton",
#     "Kc_mid_cotton",
#     "Kc_end_cotton",
#     "Kmin_cotton",
#     "Kmax_cotton",
#     "GS_start_rice",
#     "GS_end_rice",
#     "L_ini_rice",
#     "L_dev_rice",
#     "L_mid_rice",
#     "Kc_ini_rice",
#     "Kc_mid_rice",
#     "Kc_end_rice",
#     "Kmin_rice",
#     "Kmax_rice",
#     "GS_start_sorghum",
#     "GS_end_sorghum",
#     "L_ini_sorghum",
#     "L_dev_sorghum",
#     "L_mid_sorghum",
#     "Kc_ini_sorghum",
#     "Kc_mid_sorghum",
#     "Kc_end_sorghum",
#     "Kmin_sorghum",
#     "Kmax_sorghum",
#     "GS_start_soybeans",
#     "GS_end_soybeans",
#     "L_ini_soybeans",
#     "L_dev_soybeans",
#     "L_mid_soybeans",
#     "Kc_ini_soybeans",
#     "Kc_mid_soybeans",
#     "Kc_end_soybeans",
#     "Kmin_soybeans",
#     "Kmax_soybeans",
#     "GS_start_wheat",
#     "GS_end_wheat",
#     "L_ini_wheat",
#     "L_dev_wheat",
#     "L_mid_wheat",
#     "Kc_ini_wheat",
#     "Kc_mid_wheat",
#     "Kc_end_wheat",
#     "Kmin_wheat",
#     "Kmax_wheat",
# ]
